### FileStreamSourceConnector 실행
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name" : "local-file-source",
  "config" : {
    "connector.class": "org.apache.kafka.connect.file.FileStreamSourceConnector",
    "file": "/tmp/test.txt",
    "task.max" : "1",
    "topic": "connect-test"
  }
}


### 커넥터 정상 작동 확인
GET http://localhost:8083/connectors/local-file-source/status
accept:application/json

### 커넥터 종료
DELETE http://localhost:8083/connectors/local-file-source

###
GET http://localhost:8083/connectors
